<a href="https://colab.research.google.com/github/jairaj023/Internship-Practice/blob/main/Day_14Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [3]:
import re
import torch
import pandas as pd
from transformers import pipeline

Upload Dataset

In [4]:
from google.colab import files
upload = files.upload()

Saving raw_jobs.csv to raw_jobs.csv

In [5]:
df = pd.read_csv("raw_jobs.csv")

In [6]:
print("Dataset Shape:", df.shape)

Dataset Shape: (10000, 9)

In [7]:
print("\nColumns:")
print(df.columns.tolist())

Columns:
['job_id', 'job_title', 'company', 'location', 'job_description', 'experience', 'education', 'salary', 'job_type']

In [8]:
display(df.head())

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB00001,Python Developer,Infosys,Remote,We are looking for a Python Developer to join ...,1-3 years,MCA,₹10-16 LPA,Part-time
1,JOB00002,Data Scientist,Infosys,"Hyderabad, Telangana",We are looking for a Data Scientist to join ou...,0-2 years,MCA,₹12-20 LPA,Remote
2,JOB00003,Data Engineer,IBM,"Bengaluru, Karnataka",We are looking for a Data Engineer to join our...,8-12 years,BCA,₹3-5 LPA,Internship
3,JOB00004,Business Analyst,Google,"Hyderabad, Telangana",We are looking for a Business Analyst to join ...,1-3 years,M.Tech,₹10-16 LPA,Remote
4,JOB00005,Business Analyst,Mphasis,"Delhi, India",We are looking for a Business Analyst to join ...,8-12 years,M.Tech,₹5-8 LPA,Remote

Check job descriptions

In [9]:
df["job_description"] = df["job_description"].fillna("").astype(str)

print(df["job_description"].iloc[0])

We are looking for a Python Developer to join our team at Infosys. The candidate will work on data, software, and business projects. Required skills include Python, SQL, Flask. Candidates should have 1-3 years of experience and a MCA. Responsibilities include developing solutions, analyzing requirements, collaborating with teams, testing applications, documenting work, and delivering high-quality results.

Load the transformer NER model

In [10]:
ner_model = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")

print("Transformer NER model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  433MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Transformer NER model loaded successfully!

Test the model

In [11]:
text = """We are looking for a Data Analyst with experience in python, SQL, Power BI, Tableau and AWS."""

results = ner_model(text)

for entity in results:
  print(entity)

{'entity_group': 'MISC', 'score': np.float32(0.55280775), 'word': 'Ana', 'start': 26, 'end': 29}
{'entity_group': 'MISC', 'score': np.float32(0.9778856), 'word': 'SQL', 'start': 61, 'end': 64}
{'entity_group': 'MISC', 'score': np.float32(0.9195456), 'word': 'Power BI', 'start': 66, 'end': 74}
{'entity_group': 'ORG', 'score': np.float32(0.9439551), 'word': 'Table', 'start': 76, 'end': 81}
{'entity_group': 'MISC', 'score': np.float32(0.6744118), 'word': '##au', 'start': 81, 'end': 83}
{'entity_group': 'MISC', 'score': np.float32(0.83242226), 'word': 'AWS', 'start': 88, 'end': 91}

Custom Skill Extraction

In [12]:
skills = [
          "Python",
          "Java",
          "C++",
          "C#",
          "JavaScript",
          "SQL",
          "MySQL",
          "PostgreSQL",
          "MongoDB",
          "Oracle",
          "AWS",
          "Azure",
          "Google Cloud",
          "GCP",
          "Power BI",
          "Tableau",
          "Excel",
          "Python",
          "Pandas",
          "Numpy",
          "Scikit-learn",
          "TensorFlow",
          "PyTorch",
          "Machine Learning",
          "Data Science",
          "React",
          "Angular",
          "Node.js",
          "Django",
          "Flask",
          "HTML",
          "CSS",
          "Docker",
          "Kubernetes",
          "Git",
          "GitHub"
          ]

Create a skill extraction function

In [13]:
def extract_skills(text, skills_list):

    text = str(text).lower()

    found_skills = []

    for skill in skills_list:
        if skill.lower() in text:
            found_skills.append(skill)

    return list(set(found_skills))

Extract skills from your dataset

In [14]:
df["extracted_skills"] = df['job_description'].apply(lambda x: extract_skills(x, skills))

display(df[['job_title', 'job_description', 'extracted_skills']].head(10))

,job_title,job_description,extracted_skills
0,Python Developer,We are looking for a Python Developer to join ...,"[Flask, SQL, Python]"
1,Data Scientist,We are looking for a Data Scientist to join ou...,"[Scikit-learn, SQL, Python, Pandas, Machine Le..."
2,Data Engineer,We are looking for a Data Engineer to join our...,"[SQL, Python]"
3,Business Analyst,We are looking for a Business Analyst to join ...,"[Power BI, SQL]"
4,Business Analyst,We are looking for a Business Analyst to join ...,"[Power BI, SQL]"
5,Software Engineer,We are looking for a Software Engineer to join...,"[C++, Git, Java, Python]"
6,Frontend Developer,We are looking for a Frontend Developer to joi...,"[Java, JavaScript, HTML, CSS, React]"
7,AI Engineer,We are looking for a AI Engineer to join our t...,[Machine Learning]
8,Frontend Developer,We are looking for a Frontend Developer to joi...,"[HTML, CSS, React]"
9,AI Engineer,We are looking for a AI Engineer to join our t...,"[Machine Learning, Python]"

Create a function for transformer entity extraction

In [15]:
def extract_entities(text):

    try:
        results = ner_model(text[:512])

        entities = []

        for entity in results:
            entities.append({
                "word": entity["word"],
                "entity": entity["entity_group"],
                "score": round(float(entity["score"]), 3)
            })

        return entities

    except Exception as e:
        return []

Test on one job description

In [16]:
sample_text = df["job_description"].iloc[0]

entities = extract_entities(sample_text)

print("Job Description:\n")
print(sample_text)

print("\nExtracted Entities:\n")

for entity in entities:
    print(
        f"{entity['word']} → "
        f"{entity['entity']} "
        f"(Score: {entity['score']})"
    )

Job Description:

We are looking for a Python Developer to join our team at Infosys. The candidate will work on data, software, and business projects. Required skills include Python, SQL, Flask. Candidates should have 1-3 years of experience and a MCA. Responsibilities include developing solutions, analyzing requirements, collaborating with teams, testing applications, documenting work, and delivering high-quality results.

Extracted Entities:

Python Develo → MISC (Score: 0.735)
In → ORG (Score: 0.998)
##fosys → ORG (Score: 0.967)
Python → MISC (Score: 0.996)
SQL → MISC (Score: 0.981)
Flas → MISC (Score: 0.826)
MCA → ORG (Score: 0.994)

Comaparison function

In [17]:
def compare_extraction(text):

  print("TEXT:")
  print(text)

  print("\n")
  print("PRETRAINED BERT NER RESULTS")
  print("\n")

  bert_results = extract_entities(text)

  if bert_results:
      for entity in bert_results:
          print(
              f"{entity['word']} → "
              f"{entity['entity']} "
              f"(Score: {entity['score']})"
          )
  else:
      print("No entities found")

  print("\n")
  print("CUSTOM SKILL EXTRACTION")
  print("\n")

  extracted = extract_skills(text, skills)

  if extracted:
    for skill in extracted:
      print(f"{skill} → SKILL")

  else:
    print("No skills found")

Test the comparison

In [18]:
test_text = """We are looking for a Data Analyst with strong experience in Python, SQL, Power BI, Tableau, AWS and Excel."""

compare_extraction(test_text)

TEXT:
We are looking for a Data Analyst with strong experience in Python, SQL, Power BI, Tableau, AWS and Excel.


PRETRAINED BERT NER RESULTS


Ana → MISC (Score: 0.545)
Python → MISC (Score: 0.99)
SQL → MISC (Score: 0.988)
Power BI → MISC (Score: 0.947)
Table → ORG (Score: 0.581)
##au → MISC (Score: 0.913)
AWS → MISC (Score: 0.97)
Excel → MISC (Score: 0.95)


CUSTOM SKILL EXTRACTION


AWS → SKILL
SQL → SKILL
Python → SKILL
Power BI → SKILL
Tableau → SKILL
Excel → SKILL

Apply to the complete dataset

In [23]:
df_test = df.head(200).copy()

df_test["transformer_entities"] = df_test['job_description'].apply(lambda x: extract_entities(x))

print("Extraction completed!")

Extraction completed!

In [24]:
display(df_test[['job_title', 'extracted_skills', 'transformer_entities']].head(10))

,job_title,extracted_skills,transformer_entities
0,Python Developer,"[Flask, SQL, Python]","[{'word': 'Python Develo', 'entity': 'MISC', '..."
1,Data Scientist,"[Scikit-learn, SQL, Python, Pandas, Machine Le...","[{'word': 'Data Scientist', 'entity': 'ORG', '..."
2,Data Engineer,"[SQL, Python]","[{'word': 'Data Engineer', 'entity': 'MISC', '..."
3,Business Analyst,"[Power BI, SQL]","[{'word': 'Google', 'entity': 'ORG', 'score': ..."
4,Business Analyst,"[Power BI, SQL]","[{'word': 'Mphasis', 'entity': 'ORG', 'score':..."
5,Software Engineer,"[C++, Git, Java, Python]","[{'word': 'Software Engineer', 'entity': 'MISC..."
6,Frontend Developer,"[Java, JavaScript, HTML, CSS, React]","[{'word': 'Frontend Develo', 'entity': 'MISC',..."
7,AI Engineer,[Machine Learning],"[{'word': 'AI Engineer', 'entity': 'MISC', 'sc..."
8,Frontend Developer,"[HTML, CSS, React]","[{'word': 'Front', 'entity': 'ORG', 'score': 0..."
9,AI Engineer,"[Machine Learning, Python]","[{'word': 'AI Engineer', 'entity': 'MISC', 'sc..."

Save the results

In [25]:
df.to_csv("job_skill_extraction_results.csv", index = False)

print("Results saved successfully!")

Results saved successfully!

Download the results

In [26]:
files.download("job_skill_extraction_results.csv")