<a href="https://colab.research.google.com/github/jairaj023/Internship-Practice/blob/main/DAY_2_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [38]:
from google.colab import files
upload = files.upload()

Saving raw_jobs.csv to raw_jobs (1).csv

In [39]:
df = pd.read_csv('raw_jobs.csv')

In [40]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB00001,Python Developer,Infosys,Remote,We are looking for a Python Developer to join ...,1-3 years,MCA,₹10-16 LPA,Part-time
1,JOB00002,Data Scientist,Infosys,"Hyderabad, Telangana",We are looking for a Data Scientist to join ou...,0-2 years,MCA,₹12-20 LPA,Remote
2,JOB00003,Data Engineer,IBM,"Bengaluru, Karnataka",We are looking for a Data Engineer to join our...,8-12 years,BCA,₹3-5 LPA,Internship
3,JOB00004,Business Analyst,Google,"Hyderabad, Telangana",We are looking for a Business Analyst to join ...,1-3 years,M.Tech,₹10-16 LPA,Remote
4,JOB00005,Business Analyst,Mphasis,"Delhi, India",We are looking for a Business Analyst to join ...,8-12 years,M.Tech,₹5-8 LPA,Remote

In [41]:
df.isnull().sum()

job_id             0
job_title          0
company            0
location           0
job_description    0
experience         0
education          0
salary             0
job_type           0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
print(df.shape)

(10000, 9)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           10000 non-null  object
 1   job_title        10000 non-null  object
 2   company          10000 non-null  object
 3   location         10000 non-null  object
 4   job_description  10000 non-null  object
 5   experience       10000 non-null  object
 6   education        10000 non-null  object
 7   salary           10000 non-null  object
 8   job_type         10000 non-null  object
dtypes: object(9)
memory usage: 703.3+ KB

In [49]:
df.describe()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
count,10000,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,20,20,12,9993,7,8,8,5
top,JOB09984,Business Analyst,LTIMindtree,"Kolkata, West Bengal",We are looking for a AI Engineer to join our t...,8-12 years,Any Graduate,₹6-10 LPA,Internship
freq,1,532,531,908,2,1462,1314,1289,2056

In [46]:
required_columns = [
    "job_id",
    "job_title",
    "company",
    "location",
    "job_description",
    "experience",
    "education",
    "salary",
    "job_type"
]

print("Required columns:", required_columns)

Required columns: ['job_id', 'job_title', 'company', 'location', 'job_description', 'experience', 'education', 'salary', 'job_type']